### ISSUE TITLE
Embed the client id and secret

### ISSUE THREAD

**Issue by yutannihilation** [teramonagi/healthplanet#4]
It seems that embedding your client id and secret is not considered a bad manner, as famous package developers do as well:
- gistr: https://github.com/ropensci/gistr/blob/master/R/gist_auth.R#L49-L50
- imguR: https://github.com/leeper/imguR/blob/master/R/imgur_login.r#L2-L3

**Comment by teramonagi** [comment]
Fixed!
- https://github.com/teramonagi/healthplanet/pull/5

**Comment by yutannihilation** [comment]
You are great!!!
